// Generated by web_artifact_build from server/src/privileged.ts. Do not edit.
import { definePrivilegedContracts, z } from "@hatch/space-sdk";

export const privileged = definePrivilegedContracts({
  renderPdfPages: {
    request: z.object({ dataBase64: z.string().min(1).max(30_000_000) }),
    response: z.object({ pagesBase64: z.array(z.string()).max(20) }),
    capabilities: [],
    timeoutMs: 45_000,
  },
  sendAuthEmail: {
    request: z.object({
      to: z.string().email().max(200),
      code: z.string().regex(/^\d{6}$/),
      purpose: z.enum(["verify_email", "reset_password"]),
    }),
    response: z.object({ delivery: z.enum(["sent", "fallback", "failed"]) }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  sendBackupEmail: {
    request: z.object({
      to: z.string().email().max(200),
      subject: z.string().min(1).max(200),
      text: z.string().min(1).max(20_000),
      attachments: z.array(z.object({
        filename: z.string().min(1).max(240),
        contentType: z.string().min(1).max(120),
        dataBase64: z.string().min(1).max(60_000_000),
      })).max(3),
    }),
    response: z.object({ delivery: z.enum(["sent", "failed"]) }),
    capabilities: [],
    timeoutMs: 60_000,
  },
  sendSecurityAlert: {
    request: z.object({
      to: z.string().email().max(200),
      subject: z.string().min(1).max(200),
      text: z.string().min(1).max(20_000),
    }),
    response: z.object({ delivery: z.enum(["sent", "failed"]) }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  createStripeCheckout: {
    request: z.object({ userId: z.number().int().positive(), companyId: z.number().int().positive(), email: z.string().email().max(200) }),
    response: z.object({ configured: z.boolean(), checkoutUrl: z.string().nullable(), missing: z.array(z.string()) }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  verifyStripeWebhook: {
    request: z.object({ payload: z.string().min(1).max(1_000_000), signature: z.string().min(1).max(2000) }),
    response: z.object({
      eventId: z.string(),
      eventType: z.enum(["checkout.session.completed", "customer.subscription.updated", "customer.subscription.deleted", "ignored"]),
      userId: z.number().int().positive().nullable(),
      customerId: z.string().nullable(),
      subscriptionId: z.string().nullable(),
      subscriptionStatus: z.string().nullable(),
      currentPeriodEnd: z.number().int().nullable(),
      cancelAtPeriodEnd: z.boolean(),
    }),
    capabilities: [],
    timeoutMs: 20_000,
  },
});
