// Generated by web_artifact_build from server/src/privileged.ts. Do not edit.
import { definePrivilegedContracts, z } from "@hatch/space-sdk";

export const privileged = definePrivilegedContracts({
  renderPdfPages: {
    request: z.object({ dataBase64: z.string().min(1).max(30_000_000) }),
    response: z.object({ pagesBase64: z.array(z.string()).max(20) }),
    capabilities: [],
    timeoutMs: 45_000,
  },
  sendAuthEmail: {
    request: z.object({
      to: z.string().email().max(200),
      code: z.string().regex(/^\d{6}$/),
      purpose: z.enum(["verify_email", "reset_password"]),
    }),
    response: z.object({ delivery: z.enum(["sent", "fallback", "failed"]) }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  sendBackupEmail: {
    request: z.object({
      to: z.string().email().max(200),
      subject: z.string().min(1).max(200),
      text: z.string().min(1).max(20_000),
      attachments: z.array(z.object({
        filename: z.string().min(1).max(240),
        contentType: z.string().min(1).max(120),
        dataBase64: z.string().min(1).max(60_000_000),
      })).max(3),
    }),
    response: z.object({ delivery: z.enum(["sent", "failed"]) }),
    capabilities: [],
    timeoutMs: 60_000,
  },
  sendSecurityAlert: {
    request: z.object({
      to: z.string().email().max(200),
      subject: z.string().min(1).max(200),
      text: z.string().min(1).max(20_000),
    }),
    response: z.object({ delivery: z.enum(["sent", "failed"]) }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  sendNudgeEmail: {
    request: z.object({
      to: z.string().email().max(200),
      subject: z.string().min(1).max(200),
      text: z.string().min(1).max(20_000),
    }),
    response: z.object({ delivery: z.enum(["sent", "failed"]) }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  createListingBumpCheckout: {
    request: z.object({
      userId: z.number().int().positive(),
      companyId: z.number().int().positive(),
      email: z.string().email().max(200),
      listingId: z.number().int().positive(),
    }),
    response: z.object({ configured: z.boolean(), checkoutUrl: z.string().nullable(), missing: z.array(z.string()) }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  createCreditPackCheckout: {
    request: z.object({
      userId: z.number().int().positive(),
      companyId: z.number().int().positive(),
      email: z.string().email().max(200),
      pack: z.enum(["5", "15"]),
    }),
    response: z.object({ configured: z.boolean(), checkoutUrl: z.string().nullable(), missing: z.array(z.string()) }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  createStripeCheckout: {
    request: z.object({ userId: z.number().int().positive(), companyId: z.number().int().positive(), email: z.string().email().max(200), plan: z.enum(["monthly", "annual", "lifetime"]).default("monthly") }),
    response: z.object({ configured: z.boolean(), checkoutUrl: z.string().nullable(), missing: z.array(z.string()) }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  verifyStripeWebhook: {
    request: z.object({ payload: z.string().min(1).max(1_000_000), signature: z.string().min(1).max(2000) }),
    response: z.object({
      eventId: z.string(),
      eventType: z.enum(["checkout.session.completed", "customer.subscription.updated", "customer.subscription.deleted", "ignored"]),
      userId: z.number().int().positive().nullable(),
      customerId: z.string().nullable(),
      subscriptionId: z.string().nullable(),
      subscriptionStatus: z.string().nullable(),
      currentPeriodEnd: z.number().int().nullable(),
      cancelAtPeriodEnd: z.boolean(),
      checkoutType: z.string().nullable(),
      plan: z.string().nullable(),
      listingId: z.number().int().positive().nullable(),
      companyId: z.number().int().positive().nullable(),
      packSize: z.number().int().nullable(),
      stripeSessionId: z.string().nullable(),
    }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  listStripeCharges: {
    request: z.object({ customerId: z.string().min(1).max(200), limit: z.number().int().min(1).max(25).default(10) }),
    response: z.object({
      charges: z.array(z.object({
        id: z.string(), amount: z.number().int(), amountRefunded: z.number().int(),
        currency: z.string(), created: z.number().int(), status: z.string(), description: z.string().nullable(),
      })),
    }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  issueStripeRefund: {
    request: z.object({ chargeId: z.string().min(1).max(200), amountCents: z.number().int().positive().max(10_000_000).optional(), reason: z.string().trim().max(500).default("") }),
    response: z.object({ id: z.string(), amount: z.number().int(), currency: z.string(), status: z.string() }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  // Admin panel Phase 1: billing surfaces (all admin-gated at the action layer).
  listStripeSubscriptions: {
    request: z.object({ status: z.enum(["active", "trialing", "past_due", "canceled", "all"]).default("all"), limit: z.number().int().min(1).max(100).default(25), startingAfter: z.string().max(200).optional() }),
    response: z.object({
      configured: z.boolean(),
      subscriptions: z.array(z.object({
        id: z.string(), customerId: z.string(), customerEmail: z.string().nullable(),
        status: z.string(), amountCents: z.number().int(), interval: z.string(),
        currentPeriodEnd: z.number().int().nullable(), cancelAtPeriodEnd: z.boolean(),
      })),
      hasMore: z.boolean(),
    }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  listStripePayments: {
    request: z.object({ limit: z.number().int().min(1).max(100).default(25), startingAfter: z.string().max(200).optional() }),
    response: z.object({
      configured: z.boolean(),
      charges: z.array(z.object({
        id: z.string(), amount: z.number().int(), amountRefunded: z.number().int(),
        currency: z.string(), created: z.number().int(), status: z.string(),
        customerEmail: z.string().nullable(), description: z.string().nullable(),
      })),
      hasMore: z.boolean(),
    }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  listStripeFailedPayments: {
    request: z.object({}),
    response: z.object({
      configured: z.boolean(),
      failed: z.array(z.object({
        invoiceId: z.string(), customerEmail: z.string().nullable(), amountCents: z.number().int(),
        currency: z.string(), status: z.string(), attemptCount: z.number().int(),
        nextRetryAt: z.number().int().nullable(), created: z.number().int(),
      })),
    }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  createStripeCoupon: {
    request: z.object({
      code: z.string().trim().min(2).max(40),
      percentOff: z.number().min(1).max(100).optional(),
      amountOffCents: z.number().int().positive().max(10_000_000).optional(),
      duration: z.enum(["once", "repeating", "forever"]).default("once"),
      durationInMonths: z.number().int().min(1).max(36).optional(),
    }),
    response: z.object({ id: z.string(), code: z.string().nullable(), percentOff: z.number().nullable(), amountOff: z.number().nullable(), duration: z.string() }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  listStripeCoupons: {
    request: z.object({ limit: z.number().int().min(1).max(100).default(25) }),
    response: z.object({
      configured: z.boolean(),
      coupons: z.array(z.object({
        id: z.string(), code: z.string().nullable(), percentOff: z.number().nullable(),
        amountOff: z.number().nullable(), currency: z.string().nullable(),
        duration: z.string(), timesRedeemed: z.number().int(),
      })),
    }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  deleteStripeCoupon: {
    request: z.object({ couponId: z.string().min(1).max(200) }),
    response: z.object({ ok: z.literal(true), id: z.string() }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  getStripeRevenueStats: {
    request: z.object({}),
    response: z.object({
      configured: z.boolean(),
      mrrCents: z.number().nullable(),
      activeSubscriptions: z.number().nullable(),
      trialing: z.number().nullable(),
      failedPayments: z.number().nullable(),
    }),
    capabilities: [],
    timeoutMs: 30_000,
  },
  // Phase 4: Google Play Billing (TWA, package com.crewkat.app). Verifies a
  // subscription purchase token against the Play Developer API
  // (purchases.subscriptionsv2.get). Never grants anything itself — it only
  // reports what Google says; the action layer decides on entitlement.
  // Unconfigured -> configured:false (graceful, no crash, no grant).
  verifyPlayPurchase: {
    request: z.object({ purchaseToken: z.string().min(1).max(2000), sku: z.string().min(1).max(200) }),
    response: z.object({
      configured: z.boolean(),
      verified: z.boolean(),
      active: z.boolean(),
      orderId: z.string().nullable(),
      expiryTimeMillis: z.string().nullable(),
      autoRenewing: z.boolean(),
      error: z.string().nullable(),
    }),
    capabilities: [],
    timeoutMs: 20_000,
  },
  // Phase 4: reports Play Billing server configuration without needing a
  // purchase token (drives the Upgrade screen's Play vs Stripe presentation).
  getPlayBillingStatus: {
    request: z.object({}),
    response: z.object({ configured: z.boolean(), sku: z.string(), packageName: z.string() }),
    capabilities: [],
    timeoutMs: 10_000,
  },
});
